# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2026 Oxford Quantum Circuits Ltd
"""Qblox-specific derived view of canonical system data.

This module describes the configuration of Qblox hardware with a single data
structure that mirrors the physical RF chain of a Qblox Cluster. Qblox modules
are control hardware devices which can control many qubits and perform readout
depending on the module type. Each tone generated by the module is called a
generator (aka physical port). A generator is a subsection of the module (often
a sequencer + local oscillator). The generator is responsible for control of a
single mode of a qubit and can be mapped to a ``frame``. This configuration
dictates the boundaries of the generated tone and is used for legalisation and
for lowering the pulse dialect to the Q1asm dialect (Qblox IR).

As an example, a single output tone is produced by combining a local oscillator with a
sequencer's NCO
(e.g. an LO at 4.4 GHz mixed with an NCO at 240 MHz yields a 4.64 GHz output). Each such
tone-generation unit is captured as a :class:`~qat.experimental.system_data.hardware.base.
Generator` bound to a physical port. The :class:`QbloxHardwareView` ties the generators
together into a derived view of
:class:`~qat.experimental.system_data.canonical.schema.CanonicalSystemData`.

The model follows the hardware building blocks documented by Qblox (see, for example, the
`QRM-RF architecture
<https://docs.qblox.com/en/main/products/architecture/modules/qrm_rf.html>`_): a Cluster is
populated with modules (``QCM``, ``QCM-RF``, ``QRM``, ``QRM-RF``, ``QRC``); each module
exposes one or more RF ports; and each port is fed by a set of sequencers and, on RF
modules, one or more local oscillators.
"""

from __future__ import annotations

from collections import defaultdict
from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field
from enum import Enum
from functools import cached_property
from types import MappingProxyType
from typing import Any

from qat.experimental.system_data.canonical.schema import (
    CanonicalSystemData,
    ChannelData,
    ExternalResourceData,
    OscillatorData,
    PortData,
)
from qat.experimental.system_data.hardware.base import (
    Generator,
    HardwareViewInterface,
    LocalOscillator,
    Sequencer,
)
from qat.experimental.system_data.hardware.qblox_config import (
    AcquireConfig,
    AwgConfig,
    InputSignalConfig,
    MarkerSwitchConfig,
    MixerConfig,
    NcoConfig,
    OutputSignalConfig,
    PulseShapingConfig,
    ScopeAcquireConfig,
    SquareWeightAcq,
    ThresholdedAcqConfig,
)


class QbloxModuleType(str, Enum):
    """The Qblox Cluster module types supported by this view.

    :cvar QCM: Baseband Qubit Control Module.
    :cvar QCM_RF: RF Qubit Control Module.
    :cvar QRM: Baseband Qubit Readout Module.
    :cvar QRM_RF: RF Qubit Readout Module.
    :cvar QRC: RF Qubit Readout and Control Module.
    """

    QCM = "QCM"
    QCM_RF = "QCM-RF"
    QRM = "QRM"
    QRM_RF = "QRM-RF"
    QRC = "QRC"


@dataclass(frozen=True, slots=True)
class QbloxModuleSpec:
    """Static description of a Qblox module's RF chain capabilities.

    This captures the invariant limits of a module type (previously spread across the
    ``*Description`` models in ``qat.backend.qblox.target_data``) grouped by the physical
    structure they describe.

    .. note:: Whether a module up/down-converts (is "RF") is *not* stored as a flag: it is
       implied by the module's output frequency range. Likewise, whether a local oscillator
       is shared is implied by the generators mapping the same
       :class:`QBloxLocalOscillator` onto multiple sequencers.

    :ivar module_type: The module type this spec describes, or ``None`` for an unresolved
        module.
    :ivar number_of_control_sequencers: Number of sequencers dedicated to control tones.
    :ivar number_of_readout_sequencers: Number of sequencers capable of acquisition.
    :ivar number_of_outputs: Number of physical output ports.
    :ivar number_of_inputs: Number of physical input ports.
    :ivar max_binned_acquisitions: Maximum number of binned acquisitions the module can
        store, or ``None`` for control-only modules.
    :ivar scope_sample_size_range: Inclusive scope-acquisition trace sample-size bounds, or
        ``None`` for control-only modules.
    """

    module_type: QbloxModuleType | None
    number_of_control_sequencers: int
    number_of_readout_sequencers: int
    number_of_outputs: int
    number_of_inputs: int
    max_binned_acquisitions: int | None
    scope_sample_size_range: tuple[int, int] | None

    def build_sequencers(
        self, config: Mapping[str, Any] | None = None
    ) -> tuple[Sequencer, ...]:
        """Build the full fixed sequencer set for a module of this type.

        When a legacy ``QbloxConfig`` payload is supplied, each sequencer is configured from
        the matching ``sequencers[index]`` entry (NCO, AWG, marker and, for readout
        sequencers, acquisition settings). Missing entries fall back to defaults.

        :param config: Optional legacy ``QbloxConfig`` payload for the module.
        :returns: The control sequencers followed by the readout sequencers, each indexed
            contiguously from zero.
        """

        sequencer_payloads = _sequencer_payloads(config)
        sequencers: list[Sequencer] = []
        index = 0
        for _ in range(self.number_of_control_sequencers):
            sequencers.append(QBloxSequencer.create(index, sequencer_payloads.get(index)))
            index += 1
        for _ in range(self.number_of_readout_sequencers):
            sequencers.append(
                QBloxReadoutSequencer.create(index, sequencer_payloads.get(index))
            )
            index += 1
        return tuple(sequencers)


#: Static specifications keyed by module type. These replace the per-module ``*Description``
#: models from ``qat.backend.qblox.target_data``.
MODULE_SPECS: Mapping[QbloxModuleType, QbloxModuleSpec] = MappingProxyType(
    {
        QbloxModuleType.QCM: QbloxModuleSpec(
            module_type=QbloxModuleType.QCM,
            number_of_control_sequencers=6,
            number_of_readout_sequencers=0,
            number_of_outputs=4,
            number_of_inputs=0,
            max_binned_acquisitions=None,
            scope_sample_size_range=None,
        ),
        QbloxModuleType.QCM_RF: QbloxModuleSpec(
            module_type=QbloxModuleType.QCM_RF,
            number_of_control_sequencers=6,
            number_of_readout_sequencers=0,
            number_of_outputs=2,
            number_of_inputs=0,
            max_binned_acquisitions=None,
            scope_sample_size_range=None,
        ),
        QbloxModuleType.QRM: QbloxModuleSpec(
            module_type=QbloxModuleType.QRM,
            number_of_control_sequencers=0,
            number_of_readout_sequencers=6,
            number_of_outputs=2,
            number_of_inputs=2,
            max_binned_acquisitions=3_000_000,
            scope_sample_size_range=(4, 16384),
        ),
        QbloxModuleType.QRM_RF: QbloxModuleSpec(
            module_type=QbloxModuleType.QRM_RF,
            number_of_control_sequencers=0,
            number_of_readout_sequencers=6,
            number_of_outputs=1,
            number_of_inputs=1,
            max_binned_acquisitions=3_000_000,
            scope_sample_size_range=(4, 16384),
        ),
        QbloxModuleType.QRC: QbloxModuleSpec(
            module_type=QbloxModuleType.QRC,
            number_of_control_sequencers=4,
            number_of_readout_sequencers=8,
            number_of_outputs=6,
            number_of_inputs=2,
            max_binned_acquisitions=7_000_000,
            scope_sample_size_range=(4, 16384),
        ),
    }
)

#: Normalised ``ExternalResourceData.object_type`` strings mapped to module types.
_OBJECT_TYPE_TO_MODULE_TYPE: Mapping[str, QbloxModuleType] = MappingProxyType(
    {
        "QCM": QbloxModuleType.QCM,
        "QCM-RF": QbloxModuleType.QCM_RF,
        "QCM_RF": QbloxModuleType.QCM_RF,
        "QRM": QbloxModuleType.QRM,
        "QRM-RF": QbloxModuleType.QRM_RF,
        "QRM_RF": QbloxModuleType.QRM_RF,
        "QRC": QbloxModuleType.QRC,
    }
)


@dataclass(frozen=True, slots=True)
class QBloxSequencer(Sequencer):
    """A Qblox sequencer: the digital side of the RF chain that drives an output tone.

    :ivar enable_sync: Whether the sequencer participates in party-line synchronisation.
    :ivar nco_config: Numerically controlled oscillator configuration.
    :ivar awg_config: Arbitrary waveform generator configuration.
    :ivar marker_switch_config: Marker override / RF switch configuration.
    """

    enable_sync: bool = True
    nco_config: NcoConfig = field(default_factory=NcoConfig)
    awg_config: AwgConfig = field(default_factory=AwgConfig)
    marker_switch_config: MarkerSwitchConfig = field(default_factory=MarkerSwitchConfig)

    @classmethod
    def kind(cls) -> str:
        """Return the hardware-specific sequencer kind."""
        return "control"

    @classmethod
    def create(
        cls, index: int, sequencer_payload: Mapping[str, Any] | None = None
    ) -> QBloxSequencer:
        """Build a sequencer identified by its index within the module.

        :param index: Zero-based sequencer index within its module.
        :param sequencer_payload: Optional legacy ``SequencerConfig`` payload used to
            populate the sync, NCO, AWG and marker configuration. Defaults are used for any
            value that is absent.
        :returns: A sequencer of this class with the resolved configuration.
        """

        payload = sequencer_payload if isinstance(sequencer_payload, Mapping) else {}
        return cls(
            fields={"index": index},
            min_values={},
            max_values={},
            enable_sync=_opt(payload, "sync_en", True),
            nco_config=_nco_config_from(payload),
            awg_config=_awg_config_from(payload),
            marker_switch_config=_marker_switch_config_from(payload),
        )


@dataclass(frozen=True, slots=True)
class QBloxReadoutSequencer(QBloxSequencer):
    """A Qblox sequencer that additionally acquires and processes the returning signal.

    In addition to the control-side NCO/AWG configuration inherited from
    :class:`QBloxSequencer`, a readout sequencer carries the acquisition configuration.

    :ivar square_weight_acquire: Non-weighed (square) acquisition configuration.
    :ivar acquire_config: General acquisition configuration.
    :ivar threshold_acquire_config: Thresholded acquisition configuration.
    """

    square_weight_acquire: SquareWeightAcq = field(default_factory=SquareWeightAcq)
    acquire_config: AcquireConfig = field(default_factory=AcquireConfig)
    threshold_acquire_config: ThresholdedAcqConfig = field(
        default_factory=ThresholdedAcqConfig
    )

    @classmethod
    def kind(cls) -> str:
        """Return the hardware-specific sequencer kind."""
        return "readout"

    @classmethod
    def create(
        cls, index: int, sequencer_payload: Mapping[str, Any] | None = None
    ) -> QBloxReadoutSequencer:
        """Build a readout sequencer identified by its index within the module.

        In addition to the control-side configuration resolved by
        :meth:`QBloxSequencer.create`, the acquisition configuration is populated from the
        legacy ``SequencerConfig`` payload. Defaults are used for any value that is absent.

        :param index: Zero-based sequencer index within its module.
        :param sequencer_payload: Optional legacy ``SequencerConfig`` payload.
        :returns: A readout sequencer with the resolved configuration.
        """

        payload = sequencer_payload if isinstance(sequencer_payload, Mapping) else {}
        return cls(
            fields={"index": index},
            min_values={},
            max_values={},
            enable_sync=_opt(payload, "sync_en", True),
            nco_config=_nco_config_from(payload),
            awg_config=_awg_config_from(payload),
            marker_switch_config=_marker_switch_config_from(payload),
            square_weight_acquire=_square_weight_acq_from(payload),
            acquire_config=_acquire_config_from(payload),
            threshold_acquire_config=_thresholded_acq_from(payload),
        )


@dataclass(frozen=True, slots=True)
class QbloxControlGenerator(Generator):
    """A single-frequency tone generator: one sequencer paired with its connected LO.

    A generator is the smallest tone-producing subsection of a module. It combines exactly
    one sequencer with the local oscillator connected to its output path to synthesise a
    single output tone. Baseband generators have no local oscillator.

    The inherited :attr:`sequencers` and :attr:`local_oscillators` tuples always hold at
    most one sequencer and one local oscillator respectively; the :attr:`sequencer` and
    :attr:`local_oscillator` properties give convenient singular access.

    :ivar output_id: Zero-based physical output the generator's tone is routed to (e.g. ``0``
        for ``out0``), derived from the sequencer connection.
    :ivar mixer_config: Mixer correction (imbalance/phase) derived from the channel.
    :ivar pulse_shaping_config: Output pulse-shaping (FIR/exponential overshoot) config.
    :ivar output_signal_config: Output attenuation and DC offset configuration.
    """

    output_id: int = field(default=0)
    mixer_config: MixerConfig = field(default_factory=MixerConfig)
    pulse_shaping_config: PulseShapingConfig = field(default_factory=PulseShapingConfig)
    output_signal_config: OutputSignalConfig = field(default_factory=OutputSignalConfig)

    @property
    def sequencer(self) -> Sequencer:
        """The single sequencer driving this generator."""
        return self.sequencers[0]

    @property
    def local_oscillator(self) -> LocalOscillator | None:
        """The local oscillator connected to this generator, or ``None`` for baseband."""
        return self.local_oscillators[0] if self.local_oscillators else None


@dataclass(frozen=True, slots=True)
class QbloxReadoutGenerator(Generator):
    """A single-frequency tone generator that also acquires the returning signal.

    Like :class:`QbloxControlGenerator`, it combines exactly one sequencer with the local
    oscillator connected to its output path to synthesise a single output tone, and
    additionally acquires and processes the returning signal on an input path.

    The inherited :attr:`sequencers` and :attr:`local_oscillators` tuples always hold at
    most one sequencer and one local oscillator respectively; the :attr:`sequencer` and
    :attr:`local_oscillator` properties give convenient singular access.

    :ivar output_id: Zero-based physical output the generator's tone is routed to (e.g. ``0``
        for ``out0``), derived from the sequencer connection.
    :ivar mixer_config: Mixer correction (imbalance/phase) derived from the channel.
    :ivar pulse_shaping_config: Output pulse-shaping (FIR/exponential overshoot) config.
    :ivar output_signal_config: Output attenuation and DC offset configuration.
    :ivar input_id: Zero-based physical input the generator acquires from (e.g. ``0`` for
        ``in0``), derived from the sequencer acquisition connection. The input shares its
        local oscillator with an output, so it defaults to the generator's ``output_id``.
    :ivar input_signal_config: Input attenuation/gain and DC offset configuration.
    :ivar scope_acquire_config: Scope acquisition configuration.
    """

    output_id: int = field(default=0)
    input_id: int = field(default=0)
    mixer_config: MixerConfig = field(default_factory=MixerConfig)
    pulse_shaping_config: PulseShapingConfig = field(default_factory=PulseShapingConfig)
    output_signal_config: OutputSignalConfig = field(default_factory=OutputSignalConfig)
    input_signal_config: InputSignalConfig = field(default_factory=InputSignalConfig)
    scope_acquire_config: ScopeAcquireConfig = field(default_factory=ScopeAcquireConfig)

    @property
    def sequencer(self) -> Sequencer:
        """The single sequencer driving this generator."""
        return self.sequencers[0]

    @property
    def local_oscillator(self) -> LocalOscillator | None:
        """The local oscillator connected to this generator, or ``None`` for baseband."""
        return self.local_oscillators[0] if self.local_oscillators else None


@dataclass(frozen=True, slots=True)
class QBloxLocalOscillator(LocalOscillator):
    """A Qblox local oscillator.

    A single instance is shared across generators when their sequencers map onto the same
    oscillator (as on ``QRM-RF``), so sharing is implied by the generator wiring rather than
    an explicit flag.

    :ivar enable: Whether the local oscillator is enabled.
    """

    enable: bool = True


@dataclass(frozen=True, slots=True)
class QbloxModule:
    """A Qblox Cluster module and the tone generators it contains.

    A module is a physical card in the Cluster (e.g. a ``QRM-RF``). It owns a set of
    :class:`QbloxGenerator` subsections, each of which produces a single frequency, together
    with the local oscillators shared across those generators. The module type and slot are
    derived from the canonical system data.

    :ivar resource_id: Identifier of the module derived from the canonical data.
    :ivar module_type: The resolved module type, or ``None`` if it could not be determined.
    :ivar spec: The static capability specification for the module.
    :ivar sequencers: The full fixed set of sequencers the module provides, built from
        :attr:`spec` (control sequencers followed by readout sequencers).
    :ivar generators: The single-frequency tone generators hosted by this module. Each
        generator maps one of the module's :attr:`sequencers` onto a local oscillator.
    :ivar local_oscillators: The distinct local oscillators used across the generators.
    :ivar slot_idx: The Cluster slot the module occupies.
    """

    resource_id: str
    slot_idx: int
    module_type: QbloxModuleType | None
    spec: QbloxModuleSpec
    sequencers: tuple[Sequencer, ...] = ()
    generators: tuple[QbloxControlGenerator, ...] = ()
    local_oscillators: tuple[QBloxLocalOscillator, ...] = ()


@dataclass(frozen=True, slots=True)
class _ModuleMeta:
    """Metadata for a module, resolved from the first port grouped into it during
    :meth:`QbloxHardwareView.derive`.

    :ivar module_type: The resolved module type.
    :ivar slot_idx: The Cluster slot the module occupies.
    :ivar resource_id: The external resource identifier backing the module.
    :ivar config: The legacy Qblox ``QbloxConfig`` payload (module- and sequencer-level
        settings) resolved from the module's port external-resource attributes, or an empty
        mapping when no config is carried through the canonical data.
    """

    module_type: QbloxModuleType
    slot_idx: int
    resource_id: str
    config: Mapping[str, Any] = field(default_factory=lambda: MappingProxyType({}))


@dataclass(frozen=True)
class QbloxHardwareView(HardwareViewInterface):
    """A Qblox-specific derived view of canonical system data.

    The view makes every module in the Cluster visible via :attr:`modules`. Each module
    holds the single-frequency :class:`QbloxGenerator` subsections that make up its RF
    chain. The flattened :attr:`generators` view aggregates the generators of every module
    to satisfy the :class:`~qat.experimental.system_data.hardware.base.HardwareViewInterface`
    contract.

    :ivar acquire_limit: Maximum number of acquisitions allowed in a single execution batch,
        drawn from the canonical system data.
    :ivar modules: The Cluster modules, each carrying its own tone generators.
    """

    acquire_limit: int
    modules: tuple[QbloxModule, ...] = ()

    @cached_property
    def generators(self) -> tuple[QbloxControlGenerator, ...]:
        """All single-frequency generators across every module."""
        return tuple(
            generator for module in self.modules for generator in module.generators
        )

    @cached_property
    def generators_by_port(self) -> Mapping[str, tuple[QbloxControlGenerator, ...]]:
        """Map each port identifier to the generators that output on it."""
        grouped: dict[str, list[QbloxControlGenerator]] = defaultdict(list)
        for generator in self.generators:
            grouped[generator.port_id].append(generator)
        return MappingProxyType({port_id: tuple(gens) for port_id, gens in grouped.items()})

    @classmethod
    def derive(cls, parent: CanonicalSystemData, **kwargs) -> QbloxHardwareView:
        """Build a Qblox hardware view from canonical system data.

        The canonical data is produced by materialising a Qblox (purr) calibration. Every
        value is derived from that data rather than hardcoded:

        * The module type is resolved from the external resource ``object_type`` or parsed
          from the port/oscillator identifiers (e.g. ``QCM-RF``); a :class:`ValueError` is
          raised if it cannot be determined.
        * The Cluster slot is read from the port's ``baseband`` attributes; a
          :class:`ValueError` is raised if it cannot be determined.
        * Ports are grouped into physical modules by ``(instrument_id, slot)``.
        * Each canonical channel becomes a :class:`QbloxGenerator`: a sequencer (readout if
          the port supports acquisition, otherwise control) paired with the channel's local
          oscillator. Sequencers are routed to outputs using the module default, i.e. each
          output receives a contiguous block of the module's sequencers (on a QCM-RF,
          sequencers 1-3 drive the first output / LO and 4-6 the second).

        :param parent: The canonical system data to derive from.
        :returns: A populated :class:`QbloxHardwareView`.
        """

        oscillators = {osc.id: osc for osc in parent.oscillators}
        ports_by_id = {port.id: port for port in parent.ports}

        module_keys, module_meta = _group_ports_into_modules(parent)
        channels_by_key = _group_channels_by_module(parent, ports_by_id, module_keys)

        modules = tuple(
            _build_module(meta, channels_by_key.get(key, ()), ports_by_id, oscillators)
            for key, meta in module_meta.items()
        )
        return cls(acquire_limit=parent.acquire_limit, modules=modules)


def _group_ports_into_modules(
    parent: CanonicalSystemData,
) -> tuple[dict[str, tuple], dict[tuple, _ModuleMeta]]:
    """Group the canonical ports into physical modules.

    Each port is assigned a module key of ``(instrument_id, slot_idx)``. A module's metadata
    is taken from the first port grouped into it.

    :param parent: The canonical system data to read ports and resources from.
    :returns: A tuple of ``(module_keys, module_meta)`` where ``module_keys`` maps each port
        identifier to its module key and ``module_meta`` maps each module key to its
        resolved :class:`_ModuleMeta`.
    """

    resources = {res.id: res for res in parent.external_resources}
    module_keys: dict[str, tuple] = {}
    first_ports: dict[tuple, tuple[QbloxModuleType, int, str]] = {}
    module_configs: dict[tuple, Mapping[str, Any]] = {}
    for port in parent.ports:
        resource = (
            resources.get(port.external_resource_id)
            if port.external_resource_id is not None
            else None
        )
        # Resolve the module type before the slot index so an unresolved module type is
        # reported first, matching the documented resolution order.
        module_type = _resolve_module_type(resource, port.id)
        slot_idx = _resolve_slot_idx(resource, port.id)
        key: tuple = (_resolve_instrument_id(resource), slot_idx)
        module_keys[port.id] = key
        if key not in first_ports:
            first_ports[key] = (
                module_type,
                slot_idx,
                port.external_resource_id or port.id,
            )
        # The config may be collapsed to a reference stub on some of a module's ports (the
        # adapter deduplicates the shared payload), so keep the first non-empty one found.
        if key not in module_configs:
            config = _resolve_qblox_config(resource)
            if config:
                module_configs[key] = config

    module_meta: dict[tuple, _ModuleMeta] = {
        key: _ModuleMeta(
            module_type=module_type,
            slot_idx=slot_idx,
            resource_id=resource_id,
            config=module_configs.get(key, MappingProxyType({})),
        )
        for key, (module_type, slot_idx, resource_id) in first_ports.items()
    }
    return module_keys, module_meta


def _group_channels_by_module(
    parent: CanonicalSystemData,
    ports_by_id: Mapping[str, PortData],
    module_keys: Mapping[str, tuple],
) -> dict[tuple, list[ChannelData]]:
    """Group the canonical channels by the module their port belongs to.

    :param parent: The canonical system data to read channels from.
    :param ports_by_id: Canonical ports keyed by identifier.
    :param module_keys: Mapping of port identifier to module key, as returned by
        :func:`_group_ports_into_modules`.
    :returns: A mapping of module key to the channels routed to that module.
    """

    channels_by_key: dict[tuple, list[ChannelData]] = defaultdict(list)
    for channel in parent.channels:
        port = ports_by_id.get(channel.port_id)
        if port is not None:
            channels_by_key[module_keys[port.id]].append(channel)
    return channels_by_key


def _build_module(
    meta: _ModuleMeta,
    module_channels: Sequence[ChannelData],
    ports_by_id: Mapping[str, PortData],
    oscillators: Mapping[str, OscillatorData],
) -> QbloxModule:
    """Build a single :class:`QbloxModule` from its resolved metadata and channels.

    :param meta: The resolved metadata describing the module.
    :param module_channels: The canonical channels routed to this module.
    :param ports_by_id: Canonical ports keyed by identifier.
    :param oscillators: Canonical oscillator records keyed by identifier.
    :returns: The populated module, including its sequencers, generators and local
        oscillators.
    :raises ValueError: If the module type is not a supported Qblox module type.
    """

    spec = MODULE_SPECS.get(meta.module_type)
    if spec is None:
        raise ValueError(f"{meta.module_type} not a supported Qblox module type")

    sequencer_pool = spec.build_sequencers(meta.config)
    allocator = _SequencerAllocator.for_module(sequencer_pool, module_channels, ports_by_id)
    generators, module_oscillators = _build_generators(
        meta, module_channels, ports_by_id, oscillators, allocator
    )

    return QbloxModule(
        resource_id=meta.resource_id,
        module_type=meta.module_type,
        spec=spec,
        sequencers=sequencer_pool,
        generators=tuple(generators),
        local_oscillators=tuple(module_oscillators.values()),
        slot_idx=meta.slot_idx,
    )


def _build_generators(
    meta: _ModuleMeta,
    module_channels: Sequence[ChannelData],
    ports_by_id: Mapping[str, PortData],
    oscillators: Mapping[str, OscillatorData],
    allocator: _SequencerAllocator,
) -> tuple[list[QbloxControlGenerator], dict[str, QBloxLocalOscillator]]:
    """Build the tone generators for a module by routing each channel to a sequencer.

    Each canonical channel becomes a :class:`QbloxGenerator` (or
    :class:`QbloxReadoutGenerator` when its port supports acquisition), pairing the
    sequencer handed out by ``allocator`` with the channel's local oscillator.

    The physical output (and, for readout, input) is taken from the sequencer connection
    routing but resolved *once per local oscillator*: on RF modules each output has its own
    LO, so every generator sharing an LO must share the same output. This keeps the
    LO-to-output pairing consistent even though sequencers are assigned by the module's
    synthetic default routing rather than the original per-sequencer connection wiring.

    On a readout module the input shares its local oscillator with an output (the QRM-RF
    ``out0``/``in0`` LO), so a readout generator's input defaults to its own output
    (``in{N}`` pairs with ``out{N}``) unless the connection explicitly routes another input
    lane.

    :param meta: The resolved metadata describing the module.
    :param module_channels: The canonical channels routed to this module.
    :param ports_by_id: Canonical ports keyed by identifier.
    :param oscillators: Canonical oscillator records keyed by identifier.
    :param allocator: The sequencer allocator implementing the module's default routing.
    :returns: A tuple of the built generators and the local oscillators used across them,
        keyed by oscillator identifier.
    """

    generators: list[QbloxControlGenerator] = []
    module_oscillators: dict[str, QBloxLocalOscillator] = {}
    module_payload = _module_payload(meta.config)
    sequencer_payloads = _sequencer_payloads(meta.config)
    # The output/input a local oscillator pairs with, resolved from the first generator that
    # references it and reused by every generator sharing that LO.
    lo_output_id: dict[str, int] = {}
    lo_input_id: dict[str, int] = {}
    for channel in module_channels:
        port = ports_by_id[channel.port_id]
        local_oscillator = _resolve_local_oscillator(
            channel, oscillators, module_oscillators
        )
        local_oscillators = (local_oscillator,) if local_oscillator is not None else ()
        sequencer = allocator.allocate(port, meta.resource_id)
        sequencer_payload = sequencer_payloads.get(int(sequencer.fields["index"]), {})
        output_id = _resolve_output_id(
            local_oscillator,
            sequencer_payload,
            allocator.output_index.get(port.id, 0),
            lo_output_id,
        )
        if port.acquire_allowed:
            generators.append(
                QbloxReadoutGenerator(
                    port_id=port.id,
                    sample_time=port.sample_time,
                    sequencers=(sequencer,),
                    local_oscillators=local_oscillators,
                    output_id=output_id,
                    input_id=_resolve_input_id(
                        local_oscillator, sequencer_payload, output_id, lo_input_id
                    ),
                    mixer_config=_derive_mixer_config(channel),
                    output_signal_config=_output_signal_config_from(
                        module_payload, output_id
                    ),
                    input_signal_config=_input_signal_config_from(module_payload),
                    scope_acquire_config=_scope_acquire_config_from(module_payload),
                )
            )
        else:
            generators.append(
                QbloxControlGenerator(
                    port_id=port.id,
                    sample_time=port.sample_time,
                    sequencers=(sequencer,),
                    local_oscillators=local_oscillators,
                    output_id=output_id,
                    mixer_config=_derive_mixer_config(channel),
                    output_signal_config=_output_signal_config_from(
                        module_payload, output_id
                    ),
                )
            )
    return generators, module_oscillators


def _resolve_output_id(
    local_oscillator: QBloxLocalOscillator | None,
    sequencer_payload: Mapping[str, Any],
    default: int,
    lo_output_id: dict[str, int],
) -> int:
    """Resolve the output a generator drives, keeping it consistent per local oscillator.

    The output is derived from the sequencer connection routing. When the generator has a
    local oscillator the result is cached against it so that every generator sharing that LO
    reports the same output (each RF output has its own LO).

    :param local_oscillator: The generator's local oscillator, or ``None`` for baseband.
    :param sequencer_payload: The legacy ``SequencerConfig`` payload for the sequencer.
    :param default: The default output index to fall back to.
    :param lo_output_id: Cache mapping oscillator id to resolved output, updated in place.
    :returns: The resolved zero-based output index.
    """

    resolved = _output_id_from_connection(sequencer_payload, default)
    if local_oscillator is None:
        return resolved
    return lo_output_id.setdefault(local_oscillator.id, resolved)


def _resolve_input_id(
    local_oscillator: QBloxLocalOscillator | None,
    sequencer_payload: Mapping[str, Any],
    default: int,
    lo_input_id: dict[str, int],
) -> int:
    """Resolve the input a readout generator acquires from, consistent per local oscillator.

    Mirrors :func:`_resolve_output_id` for the acquisition path: the input is derived from
    the sequencer connection routing and cached against the shared local oscillator. Because
    the input shares its LO with an output, the default should be that output's index so that
    ``in{N}`` pairs with ``out{N}`` when the connection carries no explicit input lane.

    :param local_oscillator: The generator's local oscillator, or ``None`` for baseband.
    :param sequencer_payload: The legacy ``SequencerConfig`` payload for the sequencer.
    :param default: The default input index to fall back to (typically the generator's
        resolved output index, as the input shares that output's LO).
    :param lo_input_id: Cache mapping oscillator id to resolved input, updated in place.
    :returns: The resolved zero-based input index.
    """

    resolved = _input_id_from_connection(sequencer_payload, default)
    if local_oscillator is None:
        return resolved
    return lo_input_id.setdefault(local_oscillator.id, resolved)


@dataclass
class _SequencerAllocator:
    """Assigns sequencers to a module's ports using the default contiguous-block routing.

    A module's sequencers are split into contiguous blocks, one per used output (port), so
    that each output drives a fixed subset of sequencers by default (on a QCM-RF, sequencers
    0-2 drive the first output / LO and 3-5 the second). Control and readout sequencers are
    routed independently. The allocator hands out the sequencers of each block in order and
    guards against more channels being mapped to a port than its block can hold.

    :ivar control_sequencers: The module's control sequencers.
    :ivar readout_sequencers: The module's readout sequencers.
    :ivar next_offset: The next sequencer offset to hand out for each port.
    :ivar start_offset: The first sequencer offset of each port's routing block.
    :ivar control_block: The routing block size for control outputs.
    :ivar readout_block: The routing block size for readout outputs.
    :ivar output_index: The zero-based output index of each port within its direction (used
        to select per-output module settings such as attenuation and offsets).
    """

    control_sequencers: list[Sequencer]
    readout_sequencers: list[Sequencer]
    next_offset: dict[str, int]
    start_offset: dict[str, int]
    control_block: int
    readout_block: int
    output_index: dict[str, int]

    @classmethod
    def for_module(
        cls,
        sequencer_pool: Sequence[Sequencer],
        module_channels: Sequence[ChannelData],
        ports_by_id: Mapping[str, PortData],
    ) -> _SequencerAllocator:
        """Build an allocator for a module's sequencer pool and channels.

        :param sequencer_pool: The full fixed set of sequencers the module provides.
        :param module_channels: The canonical channels routed to this module.
        :param ports_by_id: Canonical ports keyed by identifier.
        :returns: An allocator primed with the module's default routing.
        """

        control_ports: list[str] = []
        readout_ports: list[str] = []
        for channel in module_channels:
            port = ports_by_id[channel.port_id]
            targets = readout_ports if port.acquire_allowed else control_ports
            if port.id not in targets:
                targets.append(port.id)

        control_sequencers = [
            seq for seq in sequencer_pool if not isinstance(seq, QBloxReadoutSequencer)
        ]
        readout_sequencers = [
            seq for seq in sequencer_pool if isinstance(seq, QBloxReadoutSequencer)
        ]
        control_block = _sequencers_per_output(len(control_sequencers), len(control_ports))
        readout_block = _sequencers_per_output(len(readout_sequencers), len(readout_ports))

        start_offset: dict[str, int] = {
            port_id: index * control_block for index, port_id in enumerate(control_ports)
        }
        start_offset.update(
            {port_id: index * readout_block for index, port_id in enumerate(readout_ports)}
        )
        output_index: dict[str, int] = {
            port_id: index for index, port_id in enumerate(control_ports)
        }
        output_index.update({port_id: index for index, port_id in enumerate(readout_ports)})
        return cls(
            control_sequencers=control_sequencers,
            readout_sequencers=readout_sequencers,
            next_offset=dict(start_offset),
            start_offset=start_offset,
            control_block=control_block,
            readout_block=readout_block,
            output_index=output_index,
        )

    def allocate(self, port: PortData, module_id: str) -> Sequencer:
        """Hand out the next sequencer for a port within its routing block.

        :param port: The port to allocate a sequencer for.
        :param module_id: The identifier of the owning module, used in error messages.
        :returns: The next sequencer in the port's routing block.
        :raises ValueError: If the port's routing block is exhausted, i.e. more channels are
            mapped to the port than it can drive.
        """

        offset = self.next_offset[port.id]
        block = self.readout_block if port.acquire_allowed else self.control_block
        if offset >= self.start_offset[port.id] + block:
            raise ValueError(
                f"Too many channels mapped to port {port.id!r} for module {module_id!r}"
            )
        self.next_offset[port.id] = offset + 1
        pool = self.readout_sequencers if port.acquire_allowed else self.control_sequencers
        return pool[offset]


def _attr_dict(resource: ExternalResourceData | None) -> dict:
    """Return an external resource's attributes as a dictionary.

    :param resource: The external resource to read, if any.
    :returns: The attribute entries as a dictionary, or an empty dictionary.
    """

    if resource is None:
        return {}
    return {attribute.key: attribute.value for attribute in resource.attributes}


def _module_type_from_id(text: str | None) -> QbloxModuleType | None:
    """Parse a module type from an identifier string.

    Identifiers materialised from purr embed the module type, for example
    ``A-CH-QCM-RF-2`` or ``A-LO-0-QRM-RF-14``. RF and hybrid variants are checked first so
    that, for example, ``QCM-RF`` is not misread as ``QCM``.

    :param text: The identifier to parse.
    :returns: The parsed module type, or ``None`` if none is present.
    """

    if not text:
        return None
    upper = text.upper()
    for token in ("QCM-RF", "QRM-RF", "QRC", "QCM", "QRM"):
        if token in upper:
            return QbloxModuleType(token)
    return None


def _slot_from_id(text: str | None) -> int | None:
    """Parse a Cluster slot index from the trailing segment of an identifier.

    :param text: The identifier to parse, for example ``A-CH-QCM-RF-2``.
    :returns: The slot index if the identifier ends in a number, otherwise ``None``.
    """

    if not text:
        return None
    tail = text.rsplit("-", 1)[-1]
    return int(tail) if tail.isdigit() else None


def _resolve_module_type(
    resource: ExternalResourceData | None, fallback_id: str | None = None
) -> QbloxModuleType:
    """Resolve the module type from an external resource or an identifier.

    The resource ``object_type`` is consulted first (for synthetic data that sets it
    directly), then the resource and fallback identifiers are parsed.

    :param resource: The external resource backing a module, if any.
    :param fallback_id: An identifier to parse if the resource does not resolve.
    :returns: The resolved module type.
    :raises ValueError: If the module type cannot be determined.
    """

    if resource is not None and resource.object_type is not None:
        mapped = _OBJECT_TYPE_TO_MODULE_TYPE.get(resource.object_type.strip().upper())
        if mapped is not None:
            return mapped
    for text in ((resource.id if resource else None), fallback_id):
        module_type = _module_type_from_id(text)
        if module_type is not None:
            return module_type
    raise ValueError(
        "Could not determine module type for resource "
        f"{resource.id if resource else None!r} / {fallback_id!r}"
    )


def _resolve_slot_idx(
    resource: ExternalResourceData | None, fallback_id: str | None = None
) -> int:
    """Resolve the Cluster slot index from a resource or an identifier.

    The port's ``baseband`` attribute is consulted first, then top-level ``slot_idx``/
    ``slot`` attributes, then the resource and fallback identifiers are parsed.

    :param resource: The external resource backing a module, if any.
    :param fallback_id: An identifier to parse if the resource does not resolve.
    :returns: The resolved slot index.
    :raises ValueError: If the slot index cannot be determined.
    """

    attributes = _attr_dict(resource)
    baseband = attributes.get("baseband")
    if isinstance(baseband, dict) and baseband.get("slot_idx") is not None:
        return int(baseband["slot_idx"])
    for attribute_key in ("slot_idx", "slot"):
        if attributes.get(attribute_key) is not None:
            return int(attributes[attribute_key])
    for text in ((resource.id if resource else None), fallback_id):
        slot_idx = _slot_from_id(text)
        if slot_idx is not None:
            return slot_idx
    raise ValueError("Could not determine slot index")


def _resolve_instrument_id(resource: ExternalResourceData | None) -> str | None:
    """Resolve the controlling instrument identifier from a resource's baseband.

    :param resource: The external resource backing a module, if any.
    :returns: The instrument identifier if present, otherwise ``None``.
    """
    baseband = _attr_dict(resource).get("baseband")
    if isinstance(baseband, dict):
        return baseband.get("instrument_id")
    return None


def _resolve_local_oscillator(
    channel: ChannelData,
    oscillators: Mapping[str, OscillatorData],
    module_oscillators: dict[str, QBloxLocalOscillator],
) -> QBloxLocalOscillator | None:
    """Resolve the local oscillator connected to a channel's generator.

    A channel that does not reference an oscillator (e.g. on a baseband module) has no local
    oscillator, so ``None`` is returned. Resolved oscillators are cached in
    ``module_oscillators`` so that generators sharing a local oscillator reference the same
    instance; that shared wiring is what implies a shared-LO module (as on ``QRM-RF``).

    :param channel: The canonical channel defining the generated frequency.
    :param oscillators: Canonical oscillator records keyed by identifier.
    :param module_oscillators: Cache of local oscillators already built for the module,
        keyed by oscillator identifier and updated in place.
    :returns: The connected local oscillator, or ``None`` if the channel has none.
    """

    if channel.oscillator_reference is None:
        return None
    oscillator = oscillators.get(channel.oscillator_reference)
    if oscillator is None:
        raise ValueError(
            f"Channel {channel.id!r} references unknown oscillator {channel.oscillator_reference!r}"
        )
    local_oscillator = module_oscillators.get(oscillator.id)
    if local_oscillator is None:
        local_oscillator = QBloxLocalOscillator(
            id=oscillator.id,
            frequency=oscillator.frequency,
        )
        module_oscillators[oscillator.id] = local_oscillator
    return local_oscillator


def _sequencers_per_output(sequencer_count: int, output_count: int) -> int:
    """Return the number of sequencers in each output's default routing block.

    A module's sequencers are split into contiguous blocks, one per output, so that each
    output drives a fixed subset of sequencers by default (e.g. on a QCM-RF the six control
    sequencers split into two blocks of three, one per output / local oscillator). When a
    direction has no used outputs the full count is returned so callers can index safely.

    :param sequencer_count: Number of sequencers available for the direction.
    :param output_count: Number of distinct outputs (ports) used in the direction.
    :returns: The block size, at least one, or the full count when there are no outputs.
    """

    if output_count <= 0:
        return sequencer_count or 1
    return max(sequencer_count // output_count, 1)


def _derive_mixer_config(channel: ChannelData) -> MixerConfig:
    """Derive the mixer correction configuration for a channel's generator.

    The mixer imbalance and phase-offset corrections are read straight from the channel
    calibration.

    :param channel: The canonical channel defining the generated tone.
    :returns: A populated :class:`MixerConfig`.
    """

    return MixerConfig(
        phase_offset=channel.phase_offset,
        gain_ratio=channel.imbalance,
    )


def _opt(mapping: Mapping[str, Any], key: str, default: Any) -> Any:
    """Return ``mapping[key]`` when present and not ``None``, otherwise ``default``.

    Legacy Qblox config payloads use ``None`` to mean "unset", so an unset value falls back
    to the config dataclass default rather than overwriting it with ``None``.

    :param mapping: The payload to read from.
    :param key: The key to look up.
    :param default: The fallback used when the value is missing or ``None``.
    :returns: The resolved value or the default.
    """

    value = mapping.get(key)
    return default if value is None else value


def _sub(mapping: Mapping[str, Any], key: str) -> Mapping[str, Any]:
    """Return a nested payload mapping, or an empty mapping when it is absent.

    :param mapping: The parent payload.
    :param key: The nested key to read.
    :returns: The nested mapping, or an empty mapping.
    """

    value = mapping.get(key)
    return value if isinstance(value, Mapping) else {}


def _resolve_qblox_config(
    resource: ExternalResourceData | None,
) -> Mapping[str, Any]:
    """Resolve the legacy ``QbloxConfig`` payload from a module's port resource.

    The config is materialised into the port external-resource attributes under
    ``baseband.config``. The materialisation adapter collapses the shared payload to a
    reference stub on repeated occurrences, so a stub (a mapping without ``module`` or
    ``sequencers``) is treated as absent.

    :param resource: The external resource backing a module port, if any.
    :returns: The ``QbloxConfig`` payload, or an empty mapping when none is available.
    """

    baseband = _attr_dict(resource).get("baseband")
    config = baseband.get("config") if isinstance(baseband, Mapping) else None
    if not isinstance(config, Mapping):
        return {}
    if "module" not in config and "sequencers" not in config:
        return {}
    return config


def _module_payload(config: Mapping[str, Any]) -> Mapping[str, Any]:
    """Return the ``module`` sub-payload of a ``QbloxConfig`` payload.

    :param config: The ``QbloxConfig`` payload.
    :returns: The module payload, or an empty mapping.
    """

    return _sub(config, "module")


def _sequencer_payloads(
    config: Mapping[str, Any] | None,
) -> Mapping[int, Mapping[str, Any]]:
    """Return the per-sequencer payloads of a ``QbloxConfig`` payload keyed by index.

    :param config: The ``QbloxConfig`` payload, if any.
    :returns: A mapping of integer sequencer index to its ``SequencerConfig`` payload.
    """

    sequencers = config.get("sequencers") if isinstance(config, Mapping) else None
    if not isinstance(sequencers, Mapping):
        return {}
    payloads: dict[int, Mapping[str, Any]] = {}
    for key, value in sequencers.items():
        try:
            index = int(key)
        except (TypeError, ValueError):
            continue
        if isinstance(value, Mapping):
            payloads[index] = value
    return payloads


def _parse_lane_index(value: Any, prefix: str) -> int | None:
    """Parse a Qblox connection lane label such as ``out0`` or ``in1`` into its index.

    :param value: The lane label to parse.
    :param prefix: The expected lane prefix (``"out"`` or ``"in"``).
    :returns: The trailing lane index, or ``None`` when the label does not match.
    """

    if not isinstance(value, str):
        return None
    text = value.strip().lower()
    tail = text[len(prefix) :]
    if text.startswith(prefix) and tail.isdigit():
        return int(tail)
    return None


def _output_id_from_connection(sequencer_payload: Mapping[str, Any], default: int) -> int:
    """Resolve the physical output a generator drives from its sequencer connection.

    The sequencer's ``connection.bulk_value`` (e.g. ``["out0"]``) is consulted first, then
    the per-lane ``out0``..``out3`` routing (``'I'``/``'Q'`` mean the lane is driven,
    ``'off'`` means it is not). When the connection carries no output routing the module's
    default output routing block is used.

    :param sequencer_payload: The legacy ``SequencerConfig`` payload for the generator's
        sequencer.
    :param default: The default output index to fall back to.
    :returns: The zero-based physical output index.
    """

    connection = _sub(sequencer_payload, "connection")
    for value in connection.get("bulk_value") or ():
        parsed = _parse_lane_index(value, "out")
        if parsed is not None:
            return parsed
    for index in range(6):
        lane = connection.get(f"out{index}")
        if isinstance(lane, str) and lane.strip().lower() not in ("", "off"):
            return index
    return default


def _input_id_from_connection(sequencer_payload: Mapping[str, Any], default: int) -> int:
    """Resolve the physical input a readout generator acquires from.

    The sequencer's ``connection.bulk_value`` (e.g. ``["out0", "in0"]``) is consulted first,
    then the acquisition lane routing (``acq_I``/``acq``/``acq_Q``, each ``in0``/``in1``).
    When the connection carries no input routing the supplied default is used.

    :param sequencer_payload: The legacy ``SequencerConfig`` payload for the generator's
        sequencer.
    :param default: The default input index to fall back to.
    :returns: The zero-based physical input index.
    """

    connection = _sub(sequencer_payload, "connection")
    for value in connection.get("bulk_value") or ():
        parsed = _parse_lane_index(value, "in")
        if parsed is not None:
            return parsed
    for key in ("acq_I", "acq", "acq_Q"):
        parsed = _parse_lane_index(connection.get(key), "in")
        if parsed is not None:
            return parsed
    return default


def _nco_config_from(sequencer_payload: Mapping[str, Any]) -> NcoConfig:
    """Build an :class:`NcoConfig` from a legacy ``SequencerConfig`` payload."""

    nco = _sub(sequencer_payload, "nco")
    return NcoConfig(
        phase_offs=_opt(nco, "phase_offs", 0.0),
        prop_delay_comp=_opt(nco, "prop_delay_comp", 0),
        prop_delay_comp_en=_opt(nco, "prop_delay_comp_en", False),
    )


def _awg_config_from(sequencer_payload: Mapping[str, Any]) -> AwgConfig:
    """Build an :class:`AwgConfig` from a legacy ``SequencerConfig`` payload."""

    awg = _sub(sequencer_payload, "awg")
    return AwgConfig(
        gain_path0=_opt(awg, "gain_path0", 0.0),
        gain_path1=_opt(awg, "gain_path1", 0.0),
        offset_path0=_opt(awg, "offset_path0", 0.0),
        offset_path1=_opt(awg, "offset_path1", 0.0),
        mod_en=_opt(awg, "mod_en", True),
    )


def _marker_switch_config_from(sequencer_payload: Mapping[str, Any]) -> MarkerSwitchConfig:
    """Build a :class:`MarkerSwitchConfig` from a legacy ``SequencerConfig`` payload."""

    return MarkerSwitchConfig(
        marker_ovr_en=sequencer_payload.get("marker_ovr_en"),
        marker_ovr_value=sequencer_payload.get("marker_ovr_value"),
    )


def _square_weight_acq_from(sequencer_payload: Mapping[str, Any]) -> SquareWeightAcq:
    """Build a :class:`SquareWeightAcq` from a legacy ``SequencerConfig`` payload."""

    square_weight = _sub(sequencer_payload, "square_weight_acq")
    return SquareWeightAcq(
        integration_length=_opt(square_weight, "integration_length", 1024),
    )


def _thresholded_acq_from(sequencer_payload: Mapping[str, Any]) -> ThresholdedAcqConfig:
    """Build a :class:`ThresholdedAcqConfig` from a legacy ``SequencerConfig`` payload."""

    thresholded = _sub(sequencer_payload, "thresholded_acq")
    return ThresholdedAcqConfig(
        rotation=_opt(thresholded, "rotation", 1.0),
        threshold=_opt(thresholded, "threshold", 0.0),
    )


def _acquire_config_from(sequencer_payload: Mapping[str, Any]) -> AcquireConfig:
    """Build an :class:`AcquireConfig` from a legacy ``SequencerConfig`` payload."""

    ttl = _sub(sequencer_payload, "ttl_acq")
    return AcquireConfig(
        auto_bin_incr_en=ttl.get("auto_bin_incr_en"),
        demod_en_acq=sequencer_payload.get("demod_en_acq"),
    )


def _output_signal_config_from(
    module_payload: Mapping[str, Any], output_index: int
) -> OutputSignalConfig:
    """Build an :class:`OutputSignalConfig` for a generator's output path.

    :param module_payload: The ``ModuleConfig`` payload.
    :param output_index: Zero-based index of the output (``out0``/``out1``) this generator
        drives.
    :returns: The resolved output signal configuration.
    """

    attenuation = _sub(module_payload, "attenuation")
    offset = _sub(module_payload, "offset")
    return OutputSignalConfig(
        attenuation=_opt(attenuation, f"out{output_index}", 0.0),
        offset_path_0=_opt(offset, f"out{output_index}_path0", 0.0),
        offset_path_1=_opt(offset, f"out{output_index}_path1", 0.0),
    )


def _input_signal_config_from(module_payload: Mapping[str, Any]) -> InputSignalConfig:
    """Build an :class:`InputSignalConfig` for a readout generator's input path.

    :param module_payload: The ``ModuleConfig`` payload.
    :returns: The resolved input signal configuration.
    """

    attenuation = _sub(module_payload, "attenuation")
    gain = _sub(module_payload, "gain")
    offset = _sub(module_payload, "offset")
    return InputSignalConfig(
        attenuation=_opt(attenuation, "in0", 0.0),
        gain=_opt(gain, "in0", 0.0),
        offset_path_0=_opt(offset, "in0_path0", 0.0),
        offset_path_1=_opt(offset, "in0_path1", 0.0),
    )


def _scope_acquire_config_from(module_payload: Mapping[str, Any]) -> ScopeAcquireConfig:
    """Build a :class:`ScopeAcquireConfig` for a readout generator.

    Only ``enable_average_mode`` has a clean legacy counterpart
    (``scope_acq.avg_mode_en_path0``); the sequencer-to-scope-memory selection has no
    equivalent and keeps its default.

    :param module_payload: The ``ModuleConfig`` payload.
    :returns: The resolved scope acquisition configuration.
    """

    scope = _sub(module_payload, "scope_acq")
    return ScopeAcquireConfig(
        enable_average_mode=_opt(scope, "avg_mode_en_path0", True),
    )
