version: 2
updates:
  - package-ecosystem: pip
    registries: "*"
    directory: "/"
    insecure-external-code-execution: allow
    schedule:
      interval: "daily"
    groups:
      all-dependencies:
        patterns:
          - "*"
