changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: 🛠 Breaking Changes
      labels:
        - breaking-change
    - title: 🚀 Features
      labels:
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - bug
    - title: ⚙️ DevOps
      labels:
        - devops
    - title: 📖 Documentation
      labels:
        - documentation
    - title: 🧪 Experimental
      labels:
        - experimental
    - title: Other Changes
      labels:
        - "*"
