# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2026 Oxford Quantum Circuits Ltd

from xdsl.ir import Dialect

from qat.experimental.dialect.q1_sequence.ir.attrs import (
    AcquireConfigAttr,
    AcquisitionAttr,
    AcquisitionPathConnectionAttr,
    AwgConfigAttr,
    ConnectionAttr,
    DirectionKindAttr,
    InputConfigAttr,
    InputSignalConfigAttr,
    LocalOscillatorConfigAttr,
    MarkerOverrideConfigAttr,
    MixerCorrectionConfigAttr,
    ModuleConfigAttr,
    NcoConfigAttr,
    OutputConfigAttr,
    OutputPathConnectionAttr,
    OutputSignalConfigAttr,
    QbloxModuleKindAttr,
    RealTimePredistortionConfigAttr,
    ScopeAcquireConfigAttr,
    SequencerConfigAttr,
    SignalPathAttr,
    ThresholdedAcquireConfigAttr,
    UnweightedAcquireConfigAttr,
    WaveformAttr,
    WeightAttr,
)
from qat.experimental.dialect.q1_sequence.ir.imm_desc import (
    AcqTableIndex,
    BinCountImm,
    IntegrationLengthImm,
    SequencerIndexAttr,
    SlotIndexAttr,
    WaveformTableIndex,
    WeightTableIndex,
)
from qat.experimental.dialect.q1_sequence.ir.ops import SequenceOp, find_enclosing_sequence
from qat.experimental.dialect.q1_sequence.target import Q1SequenceTarget

Q1_sequence = Dialect(
    "q1_sequence",
    [SequenceOp],
    [
        WaveformAttr,
        WeightAttr,
        AcquisitionAttr,
        AcquisitionPathConnectionAttr,
        ConnectionAttr,
        DirectionKindAttr,
        NcoConfigAttr,
        AwgConfigAttr,
        UnweightedAcquireConfigAttr,
        ThresholdedAcquireConfigAttr,
        AcquireConfigAttr,
        MarkerOverrideConfigAttr,
        SequencerConfigAttr,
        MixerCorrectionConfigAttr,
        RealTimePredistortionConfigAttr,
        OutputSignalConfigAttr,
        InputSignalConfigAttr,
        ScopeAcquireConfigAttr,
        LocalOscillatorConfigAttr,
        OutputConfigAttr,
        OutputPathConnectionAttr,
        InputConfigAttr,
        SignalPathAttr,
        ModuleConfigAttr,
        QbloxModuleKindAttr,
        WaveformTableIndex,
        WeightTableIndex,
        AcqTableIndex,
        BinCountImm,
        IntegrationLengthImm,
        SlotIndexAttr,
        SequencerIndexAttr,
    ],
)

__all__ = [
    "AcqTableIndex",
    "AcquisitionAttr",
    "AcquisitionPathConnectionAttr",
    "BinCountImm",
    "ConnectionAttr",
    "DirectionKindAttr",
    "Q1_sequence",
    "Q1SequenceTarget",
    "OutputPathConnectionAttr",
    "SignalPathAttr",
    "SequenceOp",
    "WaveformAttr",
    "WaveformTableIndex",
    "WeightAttr",
    "WeightTableIndex",
    "find_enclosing_sequence",
]
