pipelines:
- name: rtcs
  compile: qat.pipelines.DefaultCompile
  execute: qat.pipelines.DefaultExecute
  hardware:
    hardware_type: rtcs
  default: false
- name: echo
  compile: qat.pipelines.DefaultCompile
  execute: qat.pipelines.DefaultExecute
  hardware:
    qubit_count: 8
    hardware_type: echo
  default: true