MAX_REPEATS_LIMIT: 10
PIPELINES:
- name: echo8-alt
  pipeline: qat.pipelines.echo.echo8
  default: false
- name: echo16-alt
  pipeline: qat.pipelines.echo.echo16
  default: true
- name: echo32-alt
  pipeline: qat.pipelines.echo.echo32
  default: false
- name: echo6-alt
  pipeline: qat.pipelines.echo.get_pipeline
  hardware_loader: echo6loader
  default: false

HARDWARE:
- name: echo6loader
  loader: qat.model.loaders.legacy.EchoModelLoader
  init:
    qubit_count: 6