name: 'Testing action'
description: 'Github Action to run unit tests in a poetry project'
inputs:
  python-version:
    required: true
    description: "Python version to run tests with"
runs:
  using: composite
  steps:

    - name: Set up Python 3.x
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Load cached venv
      id: cached-pip-wheels
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

    - name: Install dependancies
      if: steps.cached-pip-wheels.outputs.cache-hit != 'true'
      shell: bash
      run: poetry sync --with dev

    - name: Unit tests
      shell: bash
      run: poetry run pytest tests/ --benchmark-skip --junitxml=./reports/${{ runner.os }}_${{ steps.setup-python.outputs.python-version }}_unit_report.xml -v

    - name: Upload report
      uses: actions/upload-artifact@v4
      with:
        name: qat_${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}_unit_report
        path: reports/**
