name: 'Testing action'
description: 'Github Action to run unit tests in a poetry project'
inputs:
  python-version:
    required: true
    description: "Python version to run tests with"
  codebase:
    required: true
    description: "Path to the codebase to test, relative to the repository root"
    default: stable
  pytest-args:
    required: false
    description: "Additional arguments to pass to pytest"
outputs:
  result:
    description: "Whether the pytest step was successful or not"
    value: ${{ steps.pytest.outcome }}

runs:
  using: composite
  steps:

    - name: Install Poetry
      shell: bash
      run: |
        pipx install poetry==2.1.4

    - name: Set up Python 3.x
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'poetry'

    - name: Install dependancies
      shell: bash
      run: poetry sync --with dev

    - name: Unit tests
      shell: bash
      id: pytest
      run: poetry run pytest --benchmark-skip -v ${{ inputs.pytest-args }} --junitxml=./reports/${{ runner.os }}_${{ steps.setup-python.outputs.python-version }}_${{ inputs.codebase }}_unit_report.xml

    - name: Upload report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: qat_${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}_${{ inputs.codebase }}_unit_report
        path: reports/**
