name: 'Testing action'
description: 'Github Action to run unit tests in a poetry project'
runs:
  using: composite
  steps:

    - name: Set up Python 3.x
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Load cached venv
      id: cached-pip-wheels
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

    - name: Install dependancies
      if: steps.cached-pip-wheels.outputs.cache-hit != 'true'
      shell: bash
      run: poetry install --sync

    - name: Unit tests
      shell: bash
      run: poetry run pytest --benchmark-skip