name: Build documentation
on:
  pull_request:
    branches: [main, develop]
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Install Poetry Action
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: poetry

    - name: Install project
      run: |
        poetry sync --with docs

    - name: Build docs
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        rm -rf .gitignore
        poetry run sphinx-apidoc -f -M -e -o docs/source/ src
        git add .
        git commit -m "temporarily commiting api docs"
        poetry run sphinx-multiversion docs/source/ docs/build/
