name: Pull Request Workflow

on:
  pull_request:
    branches:
      - main

concurrency:
  group: qat-${{ github.ref }}
  cancel-in-progress: true

jobs:
  qat:
    name: QAT
    uses: ./.github/workflows/package-build.yaml
    with:
      repository: ${{ github.repository }}
      formatting-tests: true
    secrets: inherit
